<?php

namespace Database\Seeders;

use App\Models\CookieDefinition;
use Illuminate\Database\Seeder;

class CookieDefinitionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * Seeds the global cookie database with common cookies from major services.
     * This provides immediate value to users without requiring scans.
     */
    public function run(): void
    {
        $cookies = [
            // ===== NECESSARY COOKIES =====
            [
                'name' => 'PHPSESSID',
                'domain' => '*',
                'category' => 'necessary',
                'purpose' => 'Preserves user session state across page requests.',
                'duration' => 'Session',
                'duration_seconds' => 0,
                'provider' => 'Website',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => 'JSESSIONID',
                'domain' => '*',
                'category' => 'necessary',
                'purpose' => 'Preserves user session state across page requests for Java applications.',
                'duration' => 'Session',
                'duration_seconds' => 0,
                'provider' => 'Website',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => 'wordpress_logged_in_*',
                'domain' => '*',
                'category' => 'necessary',
                'purpose' => 'Used by WordPress to identify logged-in users.',
                'duration' => 'Session',
                'duration_seconds' => 0,
                'provider' => 'WordPress',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => 'wp-settings-*',
                'domain' => '*',
                'category' => 'necessary',
                'purpose' => 'Used by WordPress to store user preferences.',
                'duration' => '1 year',
                'duration_seconds' => 31536000,
                'provider' => 'WordPress',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => 'woocommerce_cart_hash',
                'domain' => '*',
                'category' => 'necessary',
                'purpose' => 'Helps WooCommerce determine when cart contents change.',
                'duration' => 'Session',
                'duration_seconds' => 0,
                'provider' => 'WooCommerce',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => 'woocommerce_items_in_cart',
                'domain' => '*',
                'category' => 'necessary',
                'purpose' => 'Stores the number of items in the shopping cart.',
                'duration' => 'Session',
                'duration_seconds' => 0,
                'provider' => 'WooCommerce',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '__stripe_mid',
                'domain' => '.stripe.com',
                'category' => 'necessary',
                'purpose' => 'Fraud prevention cookie set by Stripe payment processor.',
                'duration' => '1 year',
                'duration_seconds' => 31536000,
                'provider' => 'Stripe',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => '__stripe_sid',
                'domain' => '.stripe.com',
                'category' => 'necessary',
                'purpose' => 'Fraud prevention session cookie set by Stripe.',
                'duration' => '30 minutes',
                'duration_seconds' => 1800,
                'provider' => 'Stripe',
                'is_third_party' => true,
                'is_verified' => true,
            ],

            // ===== FUNCTIONAL COOKIES =====
            [
                'name' => 'lang',
                'domain' => '*',
                'category' => 'functional',
                'purpose' => 'Remembers the user\'s selected language version of a website.',
                'duration' => 'Session',
                'duration_seconds' => 0,
                'provider' => 'Website',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => 'locale',
                'domain' => '*',
                'category' => 'functional',
                'purpose' => 'Stores the user\'s locale preference.',
                'duration' => '1 year',
                'duration_seconds' => 31536000,
                'provider' => 'Website',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => 'lidc',
                'domain' => '.linkedin.com',
                'category' => 'functional',
                'purpose' => 'Used for routing and load balancing.',
                'duration' => '24 hours',
                'duration_seconds' => 86400,
                'provider' => 'LinkedIn',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'bcookie',
                'domain' => '.linkedin.com',
                'category' => 'functional',
                'purpose' => 'Browser identifier cookie for LinkedIn.',
                'duration' => '1 year',
                'duration_seconds' => 31536000,
                'provider' => 'LinkedIn',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'VISITOR_INFO1_LIVE',
                'domain' => '.youtube.com',
                'category' => 'functional',
                'purpose' => 'Estimates bandwidth for YouTube video playback.',
                'duration' => '6 months',
                'duration_seconds' => 15552000,
                'provider' => 'YouTube',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'YSC',
                'domain' => '.youtube.com',
                'category' => 'functional',
                'purpose' => 'Registers a unique ID for YouTube video statistics.',
                'duration' => 'Session',
                'duration_seconds' => 0,
                'provider' => 'YouTube',
                'is_third_party' => true,
                'is_verified' => true,
            ],

            // ===== ANALYTICS COOKIES =====
            [
                'name' => '_ga',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'Google Analytics cookie used to distinguish unique users.',
                'duration' => '2 years',
                'duration_seconds' => 63072000,
                'provider' => 'Google Analytics',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '_ga_*',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'Google Analytics 4 cookie used to persist session state.',
                'duration' => '2 years',
                'duration_seconds' => 63072000,
                'provider' => 'Google Analytics',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '_gid',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'Google Analytics cookie used to distinguish users.',
                'duration' => '24 hours',
                'duration_seconds' => 86400,
                'provider' => 'Google Analytics',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '_gat',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'Google Analytics cookie used to throttle request rate.',
                'duration' => '1 minute',
                'duration_seconds' => 60,
                'provider' => 'Google Analytics',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '_gat_gtag_*',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'Google Analytics cookie used to throttle request rate.',
                'duration' => '1 minute',
                'duration_seconds' => 60,
                'provider' => 'Google Analytics',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '__utma',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'Google Analytics cookie used to distinguish users and sessions.',
                'duration' => '2 years',
                'duration_seconds' => 63072000,
                'provider' => 'Google Analytics (Legacy)',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '__utmb',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'Google Analytics cookie used to determine new sessions.',
                'duration' => '30 minutes',
                'duration_seconds' => 1800,
                'provider' => 'Google Analytics (Legacy)',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '__utmc',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'Google Analytics cookie that operates with __utmb to determine new sessions.',
                'duration' => 'Session',
                'duration_seconds' => 0,
                'provider' => 'Google Analytics (Legacy)',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '__utmz',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'Google Analytics cookie that stores traffic source information.',
                'duration' => '6 months',
                'duration_seconds' => 15552000,
                'provider' => 'Google Analytics (Legacy)',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '_pk_id.*',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'Matomo Analytics visitor ID cookie.',
                'duration' => '13 months',
                'duration_seconds' => 33696000,
                'provider' => 'Matomo',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '_pk_ses.*',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'Matomo Analytics session cookie.',
                'duration' => '30 minutes',
                'duration_seconds' => 1800,
                'provider' => 'Matomo',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '_hjSessionUser_*',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'Hotjar cookie that contains the Hotjar User ID.',
                'duration' => '1 year',
                'duration_seconds' => 31536000,
                'provider' => 'Hotjar',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => '_hjSession_*',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'Hotjar cookie that holds session data.',
                'duration' => '30 minutes',
                'duration_seconds' => 1800,
                'provider' => 'Hotjar',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => '_hjAbsoluteSessionInProgress',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'Hotjar cookie used to detect the first pageview session.',
                'duration' => '30 minutes',
                'duration_seconds' => 1800,
                'provider' => 'Hotjar',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'hubspotutk',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'HubSpot cookie used for tracking visitors.',
                'duration' => '13 months',
                'duration_seconds' => 33696000,
                'provider' => 'HubSpot',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => '__hstc',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'HubSpot cookie for tracking visitors.',
                'duration' => '13 months',
                'duration_seconds' => 33696000,
                'provider' => 'HubSpot',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => '__hssc',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'HubSpot cookie for keeping track of sessions.',
                'duration' => '30 minutes',
                'duration_seconds' => 1800,
                'provider' => 'HubSpot',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => '__hssrc',
                'domain' => '*',
                'category' => 'analytics',
                'purpose' => 'HubSpot cookie to determine if the visitor has restarted their browser.',
                'duration' => 'Session',
                'duration_seconds' => 0,
                'provider' => 'HubSpot',
                'is_third_party' => true,
                'is_verified' => true,
            ],

            // ===== MARKETING COOKIES =====
            [
                'name' => '_fbp',
                'domain' => '*',
                'category' => 'marketing',
                'purpose' => 'Facebook Pixel cookie used to identify browsers for advertising.',
                'duration' => '3 months',
                'duration_seconds' => 7776000,
                'provider' => 'Meta (Facebook)',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '_fbc',
                'domain' => '*',
                'category' => 'marketing',
                'purpose' => 'Facebook Pixel cookie that stores click identifier.',
                'duration' => '3 months',
                'duration_seconds' => 7776000,
                'provider' => 'Meta (Facebook)',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => 'fr',
                'domain' => '.facebook.com',
                'category' => 'marketing',
                'purpose' => 'Facebook cookie used for advertising and tracking.',
                'duration' => '3 months',
                'duration_seconds' => 7776000,
                'provider' => 'Meta (Facebook)',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'tr',
                'domain' => '.facebook.com',
                'category' => 'marketing',
                'purpose' => 'Facebook Pixel cookie for tracking conversions.',
                'duration' => 'Session',
                'duration_seconds' => 0,
                'provider' => 'Meta (Facebook)',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => '_gcl_au',
                'domain' => '*',
                'category' => 'marketing',
                'purpose' => 'Google Ads conversion linker cookie.',
                'duration' => '3 months',
                'duration_seconds' => 7776000,
                'provider' => 'Google Ads',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '_gcl_aw',
                'domain' => '*',
                'category' => 'marketing',
                'purpose' => 'Google Ads conversion tracking cookie.',
                'duration' => '3 months',
                'duration_seconds' => 7776000,
                'provider' => 'Google Ads',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => 'IDE',
                'domain' => '.doubleclick.net',
                'category' => 'marketing',
                'purpose' => 'Google DoubleClick cookie used for serving targeted advertisements.',
                'duration' => '13 months',
                'duration_seconds' => 33696000,
                'provider' => 'Google (DoubleClick)',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'test_cookie',
                'domain' => '.doubleclick.net',
                'category' => 'marketing',
                'purpose' => 'DoubleClick cookie to check if browser supports cookies.',
                'duration' => '15 minutes',
                'duration_seconds' => 900,
                'provider' => 'Google (DoubleClick)',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'NID',
                'domain' => '.google.com',
                'category' => 'marketing',
                'purpose' => 'Google cookie used for advertising personalization.',
                'duration' => '6 months',
                'duration_seconds' => 15552000,
                'provider' => 'Google',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => '1P_JAR',
                'domain' => '.google.com',
                'category' => 'marketing',
                'purpose' => 'Google cookie that gathers website statistics.',
                'duration' => '1 month',
                'duration_seconds' => 2592000,
                'provider' => 'Google',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'ANID',
                'domain' => '.google.com',
                'category' => 'marketing',
                'purpose' => 'Google cookie used for advertising.',
                'duration' => '13 months',
                'duration_seconds' => 33696000,
                'provider' => 'Google',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => '_uetsid',
                'domain' => '*',
                'category' => 'marketing',
                'purpose' => 'Microsoft Bing Ads Universal Event Tracking cookie.',
                'duration' => '1 day',
                'duration_seconds' => 86400,
                'provider' => 'Microsoft (Bing)',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '_uetvid',
                'domain' => '*',
                'category' => 'marketing',
                'purpose' => 'Microsoft Bing Ads cookie for tracking visitors across visits.',
                'duration' => '13 months',
                'duration_seconds' => 33696000,
                'provider' => 'Microsoft (Bing)',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => 'MUID',
                'domain' => '.bing.com',
                'category' => 'marketing',
                'purpose' => 'Microsoft cookie to identify unique web browsers.',
                'duration' => '13 months',
                'duration_seconds' => 33696000,
                'provider' => 'Microsoft (Bing)',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'personalization_id',
                'domain' => '.twitter.com',
                'category' => 'marketing',
                'purpose' => 'Twitter cookie for personalized advertising.',
                'duration' => '2 years',
                'duration_seconds' => 63072000,
                'provider' => 'X (Twitter)',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'muc_ads',
                'domain' => '.twitter.com',
                'category' => 'marketing',
                'purpose' => 'Twitter cookie for advertising purposes.',
                'duration' => '2 years',
                'duration_seconds' => 63072000,
                'provider' => 'X (Twitter)',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => '_pin_unauth',
                'domain' => '*',
                'category' => 'marketing',
                'purpose' => 'Pinterest cookie for tracking conversions.',
                'duration' => '1 year',
                'duration_seconds' => 31536000,
                'provider' => 'Pinterest',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '_pinterest_sess',
                'domain' => '.pinterest.com',
                'category' => 'marketing',
                'purpose' => 'Pinterest session cookie for login and advertising.',
                'duration' => '1 year',
                'duration_seconds' => 31536000,
                'provider' => 'Pinterest',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'li_sugr',
                'domain' => '.linkedin.com',
                'category' => 'marketing',
                'purpose' => 'LinkedIn cookie for advertising targeting.',
                'duration' => '3 months',
                'duration_seconds' => 7776000,
                'provider' => 'LinkedIn',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'UserMatchHistory',
                'domain' => '.linkedin.com',
                'category' => 'marketing',
                'purpose' => 'LinkedIn cookie for ad targeting and conversion tracking.',
                'duration' => '1 month',
                'duration_seconds' => 2592000,
                'provider' => 'LinkedIn',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'AnalyticsSyncHistory',
                'domain' => '.linkedin.com',
                'category' => 'marketing',
                'purpose' => 'LinkedIn cookie for analytics.',
                'duration' => '1 month',
                'duration_seconds' => 2592000,
                'provider' => 'LinkedIn',
                'is_third_party' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'li_fat_id',
                'domain' => '*',
                'category' => 'marketing',
                'purpose' => 'LinkedIn first-party advertising cookie.',
                'duration' => '1 month',
                'duration_seconds' => 2592000,
                'provider' => 'LinkedIn',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '_tt_enable_cookie',
                'domain' => '*',
                'category' => 'marketing',
                'purpose' => 'TikTok cookie to check if cookies are enabled.',
                'duration' => '13 months',
                'duration_seconds' => 33696000,
                'provider' => 'TikTok',
                'is_third_party' => false,
                'is_verified' => true,
            ],
            [
                'name' => '_ttp',
                'domain' => '*',
                'category' => 'marketing',
                'purpose' => 'TikTok cookie for ad targeting and measurement.',
                'duration' => '13 months',
                'duration_seconds' => 33696000,
                'provider' => 'TikTok',
                'is_third_party' => false,
                'is_verified' => true,
            ],
        ];

        foreach ($cookies as $cookie) {
            CookieDefinition::updateOrCreate(
                ['cookie_name' => $cookie['name'], 'provider' => $cookie['provider']],
                [
                    'cookie_name' => $cookie['name'],
                    'category' => $cookie['category'],
                    'description' => $cookie['purpose'],
                    'duration' => $cookie['duration'],
                    'duration_seconds' => $cookie['duration_seconds'],
                    'provider' => $cookie['provider'],
                    'platform' => $cookie['provider'],
                    'source' => 'open_database',
                    'verified' => $cookie['is_verified'] ?? true,
                    'confidence_score' => 1.00,
                ]
            );
        }

        $this->command->info('Seeded ' . count($cookies) . ' cookie definitions.');
    }
}
